services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: Nginx.Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    container_name: nginx
    volumes:
      - "../:${APP_CODE_PATH_CONTAINER}"
      - "${NGINX_SITES_PATH}:/etc/nginx/conf.d/"
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80" # for web ui
      - "88:88" # for web api
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./php/
      dockerfile: PHP.Dockerfile
      args:
        - PHP_SUFIX=${PHP_SUFIX}
        - PHP_VERSION=${PHP_VERSION}
        - WORKDIR=${APP_CODE_PATH_CONTAINER}
        - PRJ_NAME=${PRJ_NAME}
    container_name: php
    environment:
      - RUN_SEED=true
    expose:
      - "9000" # Expose port for PHP-FPM
    volumes:
      - "../:${APP_CODE_PATH_CONTAINER}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
