services:
  nginx:
    image: "${NGINX_PUSHED_IMG}"
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80" # for web ui
      - "88:88" # for web api
      - "${NGINX_HOST_HTTPS_PORT}:443"
    container_name: nginx
    networks:
      - app-network
    depends_on:
      - php

  php:
    image: "${PHP_PUSHED_IMG}"
    container_name: php
    environment:
      - RUN_SEED=false
    expose:
      - "9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge